### ISSUE TITLE
Add resume

### ISSUE THREAD

**Issue by mchristineanderson** [shyndman/megananderson.design#13]
Can you add in a link to my resume and/or let me know where I should save it?
[Manderson_Resume.pdf](https://github.com/shyndman/megananderson.design/files/6298435/Manderson_Resume.pdf)

**Comment by mchristineanderson** [comment]
making a change to this! will upload another in a sec!

**Comment by mchristineanderson** [comment]
here is the updated one 
[Resume_MeganAnderson2021.pdf](https://github.com/shyndman/megananderson.design/files/6299866/Resume_MeganAnderson2021.pdf)

**Comment by shyndman** [comment]
OK, linked
