### ISSUE TITLE
Images to swap out

### ISSUE THREAD

**Issue by mchristineanderson** [shyndman/megananderson.design#18]
Can you swap in for these images?

- [x] [material-design01](https://drive.google.com/file/d/1y64jnEYW9mwdMqAkrRBWsjCwZOx3I8JE/view?usp=sharing)
- [x] [material-design02](https://drive.google.com/file/d/1VB7tf-UrDGDZywxMx0zrem6MXqZPhaMV/view?usp=sharing)
- [x] [travel *new addition, will go as the first image, but not in replace of it.* ](https://drive.google.com/file/d/1tZtVpIKHH3EOie15K6WM6OxxEYCPNc89/view?usp=sharing)
- [x] [material-tooling03](https://drive.google.com/file/d/1OPs6_pQHvLUHaCI_wxNGCxnMCbdFSd81/view?usp=sharing)
- [x] [material-design-guidelines02](https://drive.google.com/file/d/1C58tHcKbxJIyNHk-_eb-hXLxKyk8onKG/view?usp=sharing)
- [x] [material-design-guidelines03](https://drive.google.com/file/d/10rMj2RDZBFStDC2ulXgyZ4txUFeQScfW/view?usp=sharing)
- [x] [geological-time](https://drive.google.com/file/d/17GGPwc8fAHdltzySaxfLNH1GvP6Xh4WA/view?usp=sharing)

**Comment by shyndman** [comment]
Done
