### ISSUE TITLE
Increase text size on "about me"

### ISSUE THREAD

**Issue by mchristineanderson** [shyndman/megananderson.design#2]
Can you make the text size on about me larger? 24/36
Just the part that is that main block, from the header "About me" to all the text until "...something awesome"

![Screen Shot 2021-04-08 at 10 27 56 AM](https://user-images.githubusercontent.com/57683287/114054144-34c68680-9855-11eb-97d4-b4fdfa12b299.png)

**Comment by shyndman** [comment]
Fixed...but honestly, feels too big to me.
